#!/bin/bash
set -euo pipefail

sed -i --follow-symlinks "s/background = 'dark'/background = 'light'/" ~/.config/nvim/lua/raindev/opts.lua
sed -i --follow-symlinks 's/colors: \*dark/colors: \*light/' ~/.alacritty.yml
